### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by tenkabuto** [billthefarmer/melodeon#5]
This is a very fun app to play with. I still have yet to look up what a melodeon _is_, but that hasn't stopped me from using the app and recording some short clips with Audio Recorder.

I use this on my phone, and I especially like to use the Organetto layout because the tap targets are then closer together (and easier to tap correctly). I tried to use the Accordion app, but the tap targets were hard to reliably hit.

I couldn't figure out how else to contact and thank you, so hopefully you're fine with me posting this here. :)

**Comment by billthefarmer** [comment]
[Melodeon.net](http://forum.melodeon.net) for info, although in the US of A, AFAIK, a melodeon is a [pump organ](https://en.wikipedia.org/wiki/Pump_organ#Melodeon).
